
R version 4.5.1 (2025-06-13) -- "Great Square Root"
Copyright (C) 2025 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library("R.methodsS3")
R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.
> 
> message("TESTING: throw()...")
TESTING: throw()...
> 
> rbern <- function(n=1, prob=1/2) {
+   if (prob < 0 || prob > 1)
+     throw("Argument 'prob' is out of range: ", prob)
+   rbinom(n=n, size=1, prob=prob)
+ }
> 
> rbern(10, 0.4)
 [1] 1 1 0 1 1 1 0 0 0 1
> # [1] 0 1 0 0 0 1 0 0 1 0
> tryCatch({
+   rbern(10, 10*0.4)
+ }, error=function(ex) {
+   print(ex)
+ })
<simpleError in throw.default("Argument 'prob' is out of range: ", prob): Argument 'prob' is out of range: 4>
Warning message:
In throw.default("Argument 'prob' is out of range: ", prob) :
  R.methodsS3::throw() is deprecated. Use base::stop() instead, or R.oo::throw().
> 
> message("TESTING: throw()...DONE")
TESTING: throw()...DONE
> 
