
R version 4.4.2 (2024-10-31) -- "Pile of Leaves"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testthat)
> library(shiny)
> 
> test_check("shiny")
[ FAIL 2 | WARN 0 | SKIP 17 | PASS 1490 ]

══ Skipped tests (17) ══════════════════════════════════════════════════════════
• {shinytest2} is not installed (1): 'test-test-shinyAppTemplate.R:2:1'
• File system is not case-sensitive (1): 'test-app.R:36:5'
• On CRAN (15): 'test-busy-indication.R:2:3', 'test-busy-indication.R:18:3',
  'test-busy-indication.R:58:3', 'test-pkgdown.R:3:3',
  'test-reactivity.r:147:3', 'test-reactivity.r:1240:5',
  'test-reactivity.r:1240:5', 'test-stacks-deep.R:112:3',
  'test-stacks-deep.R:166:3', 'test-stacks.R:128:3', 'test-tabPanel.R:54:3',
  'test-tabPanel.R:68:3', 'test-tabPanel.R:75:3', 'test-tabPanel.R:90:3',
  'test-utils.R:177:3'

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-stacks-deep.R:237:3'): coro async generator deep stack count is low ──
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'coro'
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-stacks-deep.R:237:3
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-test-server.R:3:1'): (code run outside of `test_that()`) ───────
<packageNotFoundError/error/condition>
Error in `library(future, warn.conflicts = FALSE)`: there is no package called ‘future’
Backtrace:
    ▆
 1. └─base::library(future, warn.conflicts = FALSE) at test-test-server.R:3:1

[ FAIL 2 | WARN 0 | SKIP 17 | PASS 1490 ]
Error: Test failures
Execution halted
